spring:
  application:
    name: AddressService
  datasource:
    url: jdbc:mysql://localhost:3306/ad
    username: root
    password: Deep
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8088

  